version: 2.1

pip install -r backend/requirements.txt

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r backend/requirements.txt

      - run:
          name: Run tests
          command: python backend/manage.py test

  docker-build:
    machine: true
    steps:
      - checkout
      - run: docker build -t arttech .

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - docker-build:
          requires:
            - build